version: '3.8'

services:
  postgres-primary:
    image: postgres:14
    container_name: grant_postgres_primary
    environment:
      POSTGRES_DB: grant_test
      POSTGRES_USER: grant
      POSTGRES_PASSWORD: test_password
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grant"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres-replica:
    image: postgres:14
    container_name: grant_postgres_replica
    environment:
      POSTGRES_DB: grant_test
      POSTGRES_USER: grant
      POSTGRES_PASSWORD: test_password
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grant"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  mysql-primary:
    image: mysql:8
    container_name: grant_mysql_primary
    environment:
      MYSQL_DATABASE: grant_test
      MYSQL_USER: grant
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  mysql-replica:
    image: mysql:8
    container_name: grant_mysql_replica
    environment:
      MYSQL_DATABASE: grant_test
      MYSQL_USER: grant
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5