module Grant
  class AssociationLoader
    def self.load_associations(records : Array(Grant::Base), associations : Array(Symbol | Hash(Symbol, Array(Symbol))))
      return if records.empty? || associations.empty?

      associations.each do |association|
        case association
        when Symbol
          load_single_association(records, association)
        when Hash
          association.each do |name, nested|
            load_single_association(records, name)
            # Load nested associations on the loaded records
            nested_records = records.flat_map { |r| extract_association_records(r, name) }.compact
            load_associations(nested_records, nested)
          end
        end
      end
    end

    private def self.load_single_association(records : Array(Grant::Base), association_name : Symbol)
      return if records.empty?

      # Delegate to the per-model instance method generated by macro finished
      # inside Grant::Base's macro inherited block.  Using an instance method
      # gives us polymorphic (vtable) dispatch to the concrete class even when
      # the array element type is Grant::Base.  The method introspects all
      # @[Grant::Relationship]-annotated methods at compile time and issues a
      # single batch query per association.
      records.first._eager_batch_load(records, association_name)
    end

    private def self.extract_association_records(record : Grant::Base, association_name : Symbol)
      data = record.get_loaded_association(association_name)
      case data
      when Array(Grant::Base)
        data
      when Grant::Base
        [data]
      else
        [] of Grant::Base
      end
    end
  end
end
