version: '2'
services:
  spec:
    extends:
      file: ../docker-compose.yml
      service: spec
    environment:
      CURRENT_ADAPTER: pg
    depends_on:
      - pg
  pg:
    image: postgres:16@sha256:a3b7f434b2dc57ce85a67e171163eb8ab1a1ebcb39d27484661f26b1dfbe30d6
    environment:
      POSTGRES_PASSWORD: pass
