name: Sharding Tests
on:
  push:
    paths:
      - 'src/grant/sharding/**'
      - 'src/grant/composite_primary_key/**'
      - 'spec/**/*sharding*'
      - 'spec/**/*composite*'
      - '.github/workflows/sharding.yml'
  pull_request:
    paths:
      - 'src/grant/sharding/**'
      - 'src/grant/composite_primary_key/**'
      - 'spec/**/*sharding*'
      - 'spec/**/*composite*'
      - '.github/workflows/sharding.yml'

jobs:
  postgres-sharding:
    runs-on: ubuntu-latest
    services:
      # Configuration database for shard mapping
      postgres-config:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: config_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5400:5432
      
      # Shard 0 - Primary & Replica
      postgres-shard0-primary:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_0
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5410:5432
      
      postgres-shard0-replica:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_0
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5411:5432
      
      # Shard 1 - Primary & Replica
      postgres-shard1-primary:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5420:5432
      
      postgres-shard1-replica:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5421:5432
      
      # Shard 2 - Primary & Replica
      postgres-shard2-primary:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5430:5432
      
      postgres-shard2-replica:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5431:5432
      
      # Shard 3 - Primary & Replica
      postgres-shard3-primary:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_3
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5440:5432
      
      postgres-shard3-replica:
        image: postgres:16
        env:
          POSTGRES_USER: grant
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shard_3
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5441:5432
    
    steps:
      - name: Download source
        uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install shards
        run: shards update --ignore-crystal-version --skip-postinstall --skip-executables
      
      - name: Run sharding tests
        timeout-minutes: 15
        run: |
          # Create test script
          cat > run_sharding_tests.sh << 'EOF'
          #!/bin/bash
          set -e
          
          echo "=== Running Composite Primary Key Tests ==="
          crystal spec spec/grant/composite_primary_key_spec.cr
          
          # TODO: Add more tests as sharding features are implemented
          # echo "=== Running Shard Resolver Tests ==="
          # crystal spec spec/grant/sharding/resolvers_spec.cr
          
          # echo "=== Running Cross-Shard Query Tests ==="
          # crystal spec spec/grant/sharding/cross_shard_spec.cr
          
          # echo "=== Running Failover Tests ==="
          # crystal spec spec/grant/sharding/failover_spec.cr
          EOF
          
          chmod +x run_sharding_tests.sh
          ./run_sharding_tests.sh
        env:
          CURRENT_ADAPTER: pg
          # Configuration database
          CONFIG_DATABASE_URL: postgres://grant:password@localhost:5400/config_db
          # Shard 0
          SHARD_0_PRIMARY: postgres://grant:password@localhost:5410/shard_0
          SHARD_0_REPLICA: postgres://grant:password@localhost:5411/shard_0
          # Shard 1
          SHARD_1_PRIMARY: postgres://grant:password@localhost:5420/shard_1
          SHARD_1_REPLICA: postgres://grant:password@localhost:5421/shard_1
          # Shard 2
          SHARD_2_PRIMARY: postgres://grant:password@localhost:5430/shard_2
          SHARD_2_REPLICA: postgres://grant:password@localhost:5431/shard_2
          # Shard 3
          SHARD_3_PRIMARY: postgres://grant:password@localhost:5440/shard_3
          SHARD_3_REPLICA: postgres://grant:password@localhost:5441/shard_3
  
  mysql-sharding:
    runs-on: ubuntu-latest
    services:
      # Configuration database
      mysql-config:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: config_db
          MYSQL_USER: grant
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3300:3306
      
      # Shard 0 - Primary
      mysql-shard0-primary:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: shard_0
          MYSQL_USER: grant
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3310:3306
      
      # Shard 1 - Primary
      mysql-shard1-primary:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: shard_1
          MYSQL_USER: grant
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3320:3306
    
    steps:
      - name: Download source
        uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install shards
        run: shards update --ignore-crystal-version --skip-postinstall --skip-executables
      
      - name: Run MySQL sharding tests
        timeout-minutes: 15
        run: |
          crystal spec spec/grant/composite_primary_key_spec.cr
        env:
          CURRENT_ADAPTER: mysql
          # Configuration database
          CONFIG_DATABASE_URL: mysql://grant:password@localhost:3300/config_db
          # Shards
          SHARD_0_PRIMARY: mysql://grant:password@localhost:3310/shard_0
          SHARD_1_PRIMARY: mysql://grant:password@localhost:3320/shard_1